exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
- "**/main/java/ch/epfl/sdp/appart/database/DatabaseService.java"
- "**/main/java/ch/epfl/sdp/appart/glide/visitor/DatabaseHostVisitor.java"
- "**/main/java/ch/epfl/sdp/appart/glide/visitor/GlideBitmapLoaderVisitor.java"
- "**/main/java/ch/epfl/sdp/appart/glide/visitor/GlideLoaderVisitor.java"
- "**/main/java/ch/epfl/sdp/appart/location/LocationService.java"
- "**/main/java/ch/epfl/sdp/appart/login/LoginService.java"
- "**/main/java/ch/epfl/sdp/appart/user/User.java"
- "**/main/java/ch/epfl/sdp/appart/hilt/DatabaseModule.java"
- "**/main/java/ch/epfl/sdp/appart/hilt/HiltApplication.java"
- "**/main/java/ch/epfl/sdp/appart/hilt/LoginModule.java"
