exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
- "app/src/main/java/ch/epfl/sdp/appart/login/LoginCallback.java"
- "app/src/main/java/ch/epfl/sdp/appart/login/LoginService.java"
- "app/src/main/java/ch/epfl/sdp/appart/Database.java"
- "app/src/main/java/ch/epfl/sdp/appart/user/User.java"
- "app/src/main/java/ch/epfl/sdp/appart/hilt/FireBaseModule.java"