exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
- "**/LoginCallback.java"
- "**/LoginService.java"
- "**/Database.java"
- "**/User.java"
- "**/FireBaseModule.java"
- "**/DatabaseVisitorHost.java"
- "**/GlideLoaderVisitor.java"
- "**/LoginModule.java"
- "**/MockLoginServiceException.java"
- "**/FirebaseEmulatorLoginServiceWrapper.java"
