exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
- "**/LoginCallback.java"
- "**/LoginService.java"
- "**/Database.java"
- "**/User.java"
- "**/FireBaseModule.java"
- "**/DatabaseVisitorHost.java"
- "**/GlideLoaderVisitor.java"
- "**/LoginModule.java"
- "**/MockLoginServiceException.java"
- "**/FirebaseEmulatorLoginServiceWrapper.java"
- "**/LocationModule_ProvideGeocoderFactory.java"
- "**/LocationModule_ProvideLocationProviderFactory.java"
- "**/glide/**"
- "**/appart/hilt/**"
- "**/LocationModule.java"
- "**/*Hilt*.*"
- "hilt_aggregated_deps/**"
- "**/*_Factory.class"
- "**/*_MembersInjector.class"
